# Generated by Django 2.2.1 on 2019-05-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='download_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
